target 'iosApp' do
 use_frameworks!
  platform :ios, '14.1'

#   pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.13.0/mokoMvvmFlowSwiftUI.podspec'
  pod 'shared', :path => '../shared'

end
